services:
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - ft_onion
  
  tor:
    build: tor/
    container_name: tor
    networks:
      - ft_onion


    
networks:
  ft_onion:
    driver: bridge
