services:
  nginx:
    build: .
    stdin_open: true
    tty: true
    container_name: nginx
    ports:
      - 8080:80
      - 4242:4242
    networks:
      - ft_onion

networks:
  ft_onion:
    driver: bridge
